In [1]:
import joblib
import os
from API.utils import *
import pandas as pd
import numpy as np
os.listdir('./model')

['ANN(58_to_sp162).pkl',
 'split_factor_transformer.pkl',
 'SVR(5_to_23).pkl',
 'transformer(23_to_54).pkl',
 'transformer(SP162_to_Y162).pkl']

# load pretrained model

In [2]:
A = joblib.load('./model/SVR(5_to_23).pkl')
B = joblib.load('./model/transformer(23_to_54).pkl')
C = joblib.load('./model/ANN(58_to_sp162).pkl')
D = joblib.load('./model/transformer(SP162_to_Y162).pkl')

# input data

In [3]:
df = pd.read_csv('./data/phase_1/test_170.csv',index_col=0).head(1)
y_test = df.iloc[:,4:]
X_test = df[['T10','T50','T90','N+A']]
X_test

    T10    T50    T90     N+A
0  98.6  119.2  146.1  40.133

# step1

In [4]:
y_pred23 = A.predict(X_test)
y_pred23 = pd.DataFrame(y_pred23,columns=y_test.columns)
print(y_pred23.sum(axis=1))
y_pred23.head()

0    100.0
dtype: float64

,C5NP,C5IP,C5N,C6NP,C6IP,C6N,C6A,C7NP,C7IP,C7N,...,C8N,C8A,C9NP,C9IP,C9N,C9A,C10NP,C10IP,C10N,C10A
0,1.209731,0.820594,0.162816,3.629933,2.26249,3.564549,0.663143,8.043859,6.372003,9.585558,...,7.062309,5.898643,5.227595,9.39163,5.004924,3.514413,1.145865,5.281013,0.677925,0.696174

# step 2

In [5]:
y_pred54 = B(y_pred23)
print(y_pred54.sum(axis=1))
y_pred54.head()

0    100.0
dtype: float64

,O2,METHANE,ETHANE,PROPANE,BUTANE,IPENTANE,PENTANE,T2PENTEN,CP,3MP,...,TEMH,3MN,TBCYHXAN,DECANE,ODEBZ,UNDECANE,PNBZ,DODECANE,HXBNZN,TRIDECAN
0,0.0,0.0,0.0,0.04103,0.082059,0.681093,1.209731,0.016412,0.162816,2.21724,...,1.31768,3.075259,0.677925,0.960891,0.650992,0.181735,0.037847,0.00324,0.007335,0.0

# step3

In [6]:
case_col = ['Case Conditions_Feed Rate to C013 (Input)', 
            'Case Conditions_C7+ in Light End (Input)', 
            'Case Conditions_Heart Cut Prod. Rate (Input)', 
            'Case Conditions_C6P- in Heart Cut (Input)']
case = pd.DataFrame(index=[0],columns=case_col)
case.iloc[0,:] = [10,2.5,100,1]

y_pred58 = pd.concat([case,y_pred54],axis=1)
y_pred58

,Case Conditions_Feed Rate to C013 (Input),Case Conditions_C7+ in Light End (Input),Case Conditions_Heart Cut Prod. Rate (Input),Case Conditions_C6P- in Heart Cut (Input),O2,METHANE,ETHANE,PROPANE,BUTANE,IPENTANE,...,TEMH,3MN,TBCYHXAN,DECANE,ODEBZ,UNDECANE,PNBZ,DODECANE,HXBNZN,TRIDECAN
0,10,2.5,100,1,0.0,0.0,0.0,0.04103,0.082059,0.681093,...,1.31768,3.075259,0.677925,0.960891,0.650992,0.181735,0.037847,0.00324,0.007335,0.0

In [7]:
sp162 = C.predict(y_pred58)
print(sp162.sum(axis=1))
sp162

0    54.0
dtype: float32

,Individual Component to Light End Split Factor_Oxygen_Ratio,Individual Component to Heart Cut Split Factor_Oxygen_Ratio,Individual Component to Heavy End Split Factor_Oxygen_Ratio,Individual Component to Light End Split Factor_Methane_Ratio,Individual Component to Heart Cut Split Factor_Methane_Ratio,Individual Component to Heavy End Split Factor_Methane_Ratio,Individual Component to Light End Split Factor_Ethane_Ratio,Individual Component to Heart Cut Split Factor_Ethane_Ratio,Individual Component to Heavy End Split Factor_Ethane_Ratio,Individual Component to Light End Split Factor_Propane_Ratio,...,Individual Component to Heavy End Split Factor_n-Pentylbenzene_Ratio,Individual Component to Light End Split Factor_n-Dodecane_Ratio,Individual Component to Heart Cut Split Factor_n-Dodecane_Ratio,Individual Component to Heavy End Split Factor_n-Dodecane_Ratio,Individual Component to Light End Split Factor_n-Hexylbenzene_Ratio,Individual Component to Heart Cut Split Factor_n-Hexylbenzene_Ratio,Individual Component to Heavy End Split Factor_n-Hexylbenzene_Ratio,Individual Component to Light End Split Factor_n-Tridecane_Ratio,Individual Component to Heart Cut Split Factor_n-Tridecane_Ratio,Individual Component to Heavy End Split Factor_n-Tridecane_Ratio
0,1.0,6.841902e-08,2.097741e-07,0.999999,4.520859e-07,1.039900e-07,1.0,1.178300e-07,1.494730e-07,0.994342,...,0.431684,4.941945e-08,0.570734,0.429266,0.000008,0.559322,0.44067,6.767231e-07,0.000002,0.999998

# step4

In [8]:
xna = y_pred58.iloc[:,4:]
y_162 = D(xna,sp162)
print(y_162.sum(axis=1))
y_162

0    300.0
dtype: float64

,Light End Product Properties_Oxygen_wt%,Light End Product Properties_Methane_wt%,Light End Product Properties_Ethane_wt%,Light End Product Properties_Propane_wt%,Light End Product Properties_n-Butane_wt%,Light End Product Properties_i-Pentane_wt%,Light End Product Properties_n-Pentane_wt%,Light End Product Properties_tr2-Pentene_wt%,Light End Product Properties_Cyclopentane_wt%,Light End Product Properties_3-Methylpentane_wt%,...,"Heavy End Product Properties_2,2,3,3-Tetramethylhexane_wt%",Heavy End Product Properties_3-Methylnoe_wt%,Heavy End Product Properties_tert-Butylcyclohexane_wt%,Heavy End Product Properties_n-Decane_wt%,"Heavy End Product Properties_1,2-Diethylbenzene_wt%",Heavy End Product Properties_n-Undecane_wt%,Heavy End Product Properties_n-Pentylbenzene_wt%,Heavy End Product Properties_n-Dodecane_wt%,Heavy End Product Properties_n-Hexylbenzene_wt%,Heavy End Product Properties_n-Tridecane_wt%
0,0.0,0.0,0.0,0.433249,0.86084,7.042899,12.467262,0.168596,1.627328,20.762034,...,5.278603,13.045674,2.930748,4.330787,3.054203,0.919965,0.188227,0.016023,0.037238,0.0

In [9]:
print(y_162[D.le].sum(axis=1))
print(y_162[D.hc].sum(axis=1))
print(y_162[D.he].sum(axis=1))

0    100.0
dtype: float64
0    100.0
dtype: float64
0    100.0
dtype: float64